import { CursorEvent } from '@/lib/types';

export const events: CursorEvent[] = [
	{
		id: 'cursor-meetup-antigua',
		title: 'Cursor Meetup Antigua',
		titleLocal: 'Cursor Meetup Antigua Guatemala',
		date: '2026-03-22',
		displayDate: '22 de marzo de 2026',
		displayDates: { en: 'March 22, 2026', es: '22 de marzo de 2026' },
		location: 'Antigua Guatemala',
		recapPath: '/recaps/cursor-meetup-antigua',
		thumbnail: '/events/antigua-cursor-gt-1.jpeg',
		galleryImages: [
			'/events/antigua-cursor-gt-2.jpeg',
			'/events/antigua-cursor-gt-3.jpeg',
			'/events/antigua-cursor-gt-4.jpeg',
			'/events/antigua-cursor-gt-5.jpeg',
			'/events/antigua-cursor-gt-6.jpeg',
			'/events/antigua-cursor-gt-7.jpeg',
			'/events/antigua-cursor-gt-8.jpeg',
			'/events/antigua-cursor-gt-9.jpeg',
			'/events/antigua-cursor-gt-10.jpeg',
			'/events/antigua-cursor-gt-11.jpeg',
		],
		status: 'past',
		host: {
			name: 'El Cubo Center',
			logo: '/images/partners/el-cubo-center.svg',
			url: 'https://elcubocenter.com',
		},
	},
	{
		id: 'cursor-hackathon-guatemala',
		title: 'Cursor Hackathon Guatemala',
		titleLocal: 'Cursor Hackathon Guatemala 2026',
		date: '2026-03-07',
		displayDate: '7 de marzo de 2026',
		displayDates: { en: 'March 7, 2026', es: '7 de marzo de 2026' },
		attendees: 140,
		location: 'Universidad del Valle de Guatemala, Ciudad de Guatemala',
		recapPath: '/recaps/cursor-hackathon-guatemala',
		thumbnail: '/events/cursor-hackathon-gt-1.jpeg',
		galleryImages: [
			'/events/cursor-hackathon-gt-2.jpeg',
			'/events/cursor-hackathon-gt-3.jpeg',
			'/events/cursor-hackathon-gt-4.jpeg',
		],
		status: 'past',
		host: {
			name: 'Universidad del Valle de Guatemala',
			logo: '/images/partners/uvg.svg',
			url: 'https://www.uvg.edu.gt',
		},
	},
	{
		id: 'cafe-cursor-guatemala',
		title: 'Cafe Cursor Guatemala',
		titleLocal: 'Cafe Cursor Guatemala',
		date: '2025-12-13',
		displayDate: '13 de diciembre de 2025',
		displayDates: { en: 'December 13, 2025', es: '13 de diciembre de 2025' },
		location: 'Ciudad de Guatemala, Guatemala',
		recapPath: '/recaps/cafe-cursor-guatemala',
		thumbnail: '/events/cafe-cursor-gt-1.jpeg',
		galleryImages: [
			'/events/cafe-cursor-gt-2.jpeg',
			'/events/cafe-cursor-gt-3.jpeg',
			'/events/cafe-cursor-gt-4.jpeg',
			'/events/cafe-cursor-gt-5.jpeg',
			'/events/cafe-cursor-gt-6.jpeg',
			'/events/cafe-cursor-gt-7.jpeg',
			'/events/cafe-cursor-gt-8.jpeg',
			'/events/cafe-cursor-gt-9.jpeg',
			'/events/cafe-cursor-gt-10.jpeg',
			'/events/cafe-cursor-gt-11.jpeg',
		],
		status: 'past',
	},
	{
		id: 'first-cursor-meetup-guatemala',
		title: 'First Cursor Meetup Guatemala',
		titleLocal: 'Primer Meetup de Cursor en Guatemala',
		date: '2025-08-31',
		displayDate: '31 de agosto de 2025',
		displayDates: { en: 'August 31, 2025', es: '31 de agosto de 2025' },
		location: 'Ciudad de Guatemala, Guatemala',
		recapPath: '/recaps/first-cursor-meetup',
		thumbnail: '/events/primer-meetup-cursor-gt-1.jpeg',
		galleryImages: [
			'/events/primer-meetup-cursor-gt-2.jpeg',
			'/events/primer-meetup-cursor-gt-3.jpeg',
			'/events/primer-meetup-cursor-gt-4.jpeg',
		],
		status: 'past',
	},
];

export const upcomingEvents = events.filter((event) => event.status === 'upcoming');
export const pastEvents = events.filter((event) => event.status === 'past');
