// Images for Hero Gallery
export const galleryImages: string[] = [
	'/events/primer-meetup-cursor-gt-1.jpeg',
	'/events/antigua-cursor-gt-1.jpeg',
	'/events/antigua-cursor-gt-2.jpeg',
	'/events/cursor-event-4.jpeg',
	'/events/cafe-cursor-gt-1.jpeg',
	'/events/cafe-cursor-gt-2.jpeg',
	'/events/cafe-cursor-gt-3.jpeg',
	'/events/cafe-cursor-gt-4.jpeg',
	'/events/antigua-cursor-gt-3.jpeg',
	'/events/antigua-cursor-gt-4.jpeg',
	'/events/primer-meetup-cursor-gt-2.jpeg',
	'/events/cafe-cursor-gt-5.jpeg',
	'/events/cafe-cursor-gt-6.jpeg',
	'/events/primer-meetup-cursor-gt-3.jpeg',
	'/events/antigua-cursor-gt-5.jpeg',
	'/events/cursor-event-16.jpeg',
	'/events/antigua-cursor-gt-6.jpeg',
	'/events/cursor-event-18.jpeg',
	'/events/antigua-cursor-gt-7.jpeg',
	'/events/antigua-cursor-gt-8.jpeg',
	'/events/antigua-cursor-gt-9.jpeg',
	'/events/primer-meetup-cursor-gt-4.jpeg',
];